features:
  continuous:
    - applicant_income
    - coapplicant_income
    - loan_amount
  discrete:
    categorical:
      - dependents
      - property_area
      - gender
      - married
      - education
      - self_employed
    numerical:
      - loan_amount_term
      - credit_history
renamed_column_names:
  Gender: gender
  Married: married
  Dependents: dependents
  Education: education
  Self_Employed: self_employed
  ApplicantIncome: applicant_income
  CoapplicantIncome: coapplicant_income
  LoanAmount: loan_amount
  Loan_Amount_Term: loan_amount_term
  Credit_History: credit_history
  Property_Area: property_area
  Loan_Status: loan_status
target: loan_status
useless_cols:
  - Loan_ID
data:
  raw:
    test: data/raw/test.csv
    train: data/raw/train.csv
    entire_data: data/raw/entire_data.csv
  interim:
    test: data/interim/test.csv
    train: data/interim/train.csv
  processed:
    test: data/processed/test.csv
    train: data/processed/train.csv
train_test_split:
  test_size: 0.2
  random_state: 37
  stratify: Loan_Status
model:
  type: rfc
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
preprocessing:
  discrete:
    impute_strategy:
      most_frequent:
        - gender
        - dependents
        - married
        - self_employed
        - loan_amount_term
        - credit_history
    encode:
      oe:
        - dependents
        - property_area
      ohe:
        - gender
        - married
        - education
        - self_employed
        - loan_amount_term
  continuous:
    impute_strategy:
      mean:
        - loan_amount
    scaler: standard
