[num]
cols = [ "applicant_income", "coapplicant_income", "loan_amount",]

[cat]
cols = [ "gender", "married", "dependents", "education", "self_employed", "property_area", "loan_amount_term", "credit_history", "has_coapplicant",]
